// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdEL9f8n33UbXni6NRqeqBoWIfdjU3VAo',
    appId: '1:8264121967:web:d6cb44ab52018d1e2b179a',
    messagingSenderId: '8264121967',
    projectId: 'expensetracker-9bb87',
    authDomain: 'expensetracker-9bb87.firebaseapp.com',
    storageBucket: 'expensetracker-9bb87.firebasestorage.app',
    measurementId: 'G-S18VYG29E7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdEL9f8n33UbXni6NRqeqBoWIfdjU3VAo',
    appId: '1:8264121967:android:d6cb44ab52018d1e2b179a',
    messagingSenderId: '8264121967',
    projectId: 'expensetracker-9bb87',
    storageBucket: 'expensetracker-9bb87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdEL9f8n33UbXni6NRqeqBoWIfdjU3VAo',
    appId: '1:8264121967:ios:d6cb44ab52018d1e2b179a',
    messagingSenderId: '8264121967',
    projectId: 'expensetracker-9bb87',
    storageBucket: 'expensetracker-9bb87.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrackerApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdEL9f8n33UbXni6NRqeqBoWIfdjU3VAo',
    appId: '1:8264121967:ios:d6cb44ab52018d1e2b179a',
    messagingSenderId: '8264121967',
    projectId: 'expensetracker-9bb87',
    storageBucket: 'expensetracker-9bb87.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrackerApplication',
  );
}
